Repository spring-financial-group/peacock, pull requests merged in 2024-03, with the labels that each got.

#60 feat: store release notes in mongodb
  .gitignore
  Makefile
  charts/peacock/Chart.yaml
  charts/peacock/templates/_helpers.tpl
  charts/peacock/templates/deployment.yaml
  charts/peacock/templates/secret.yaml
  charts/peacock/values.yaml
  cmd/api/main.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/domain/git.go
  pkg/domain/mocks/FeathersUseCase.go
  pkg/domain/mocks/Git.go
  pkg/domain/mocks/MessageClient.go
  pkg/domain/mocks/MessageHandler.go
  pkg/domain/mocks/ReleaseNotesUseCase.go
  pkg/domain/mocks/ReleaseRepository.go
  pkg/domain/mocks/ReleaseUseCase.go
  pkg/domain/mocks/SCM.go
  pkg/domain/release.go
  pkg/git/github/client.go
  pkg/models/pullrequest.go
  pkg/models/release.go
  pkg/release/delivery/releasehandler.go
  pkg/release/repository/mongodb/repository.go
  pkg/release/usecase/releaseuc.go
  pkg/releasenotes/repository/mongodb/repository.go
  pkg/server/data.go
  pkg/server/datasources.go
  pkg/server/inject.go
  pkg/server/server.go
  pkg/webhook/usecase/webhookuc.go
  pkg/webhook/usecase/webhookuc_test.go
  preview/values.yaml.gotmpl
Labels: size/XXL, approved, IS

#101 chore: add package gen
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
Labels: size/S

#102 fix: add swagger copy to dockerfile
  Dockerfile
Labels: approved, size/XS

#103 feat: add cors
  charts/peacock/templates/configmap.yaml
  charts/peacock/templates/deployment.yaml
  charts/peacock/values.yaml
  development-config.yaml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/server/inject.go
Labels: approved, size/L

#104 fix: cors headers
  pkg/server/inject.go
Labels: approved, size/XS

#105 refactor: configurable cors headers
  charts/peacock/values.yaml
  development-config.yaml
  pkg/config/config.go
  pkg/server/inject.go
Labels: approved, size/S

#106 chore: remove version from secret chart
  charts/peacock/templates/secret.yaml
Labels: approved, size/XS
