Repository spring-financial-group/peacock, pull requests merged in 2025-04, with the labels that each got.

#127 fix: maybe remove the preceeding newline if it exists
  OWNERS_ALIASES
  pkg/releasenotes/usecase/releasenotesuc.go
  pkg/releasenotes/usecase/releasenotesuc_test.go
Labels: size/XS

#129 chore: update image
  .lighthouse/jenkins-x/release.yaml
Labels: approved, size/XS

#131 feat: get markdown from release notes
  pkg/domain/mocks/FeathersUseCase.go
  pkg/domain/mocks/Git.go
  pkg/domain/mocks/MessageClient.go
  pkg/domain/mocks/MessageHandler.go
  pkg/domain/mocks/ReleaseNotesUseCase.go
  pkg/domain/mocks/ReleaseRepository.go
  pkg/domain/mocks/ReleaseUseCase.go
  pkg/domain/mocks/SCM.go
  pkg/domain/releasenotes.go
  pkg/releasenotes/usecase/releasenotesuc.go
  pkg/releasenotes/usecase/releasenotesuc_test.go
Labels: approved, size/L
